#!/bin/sh
#
#sdat=$(date -d "${date} " +%Y%m%d)
sdat=20260606
favar=mx2t24
plvar='var51'
pyvar='maximum_2m_temperature_in_the_last_24_hours'
thres=20

python='nohup /mypath/anaconda3/bin/python'
cdo='/mypath/utils/opt/cdo-install/cdo-1.9.3/src/cdo'
###########################
d0=/mypath3/OPER/C3S/Prel_CRON/Module1_Forecast/Forecast/Year/Extremes/Indices_Forecast_Year/Heat_waves/Forecast
dwk=${d0}/SCR
daux=${dwk}/Auxil
dget0=${d0}/GET_data/DATA
#####################################
echo "sdat=" $sdat
yy1=$(date -d "${sdat} " +%Y)
mm1=$(date -d "${sdat} " +%m)
cmm1=$(date -d "${sdat} " +%-m)
dd1='01'

if [ ${mm1} -eq 5 ] || [ ${mm1} -eq 10 ] ;then
  thres=25
elif [ ${mm1} -eq 6 ] || [ ${mm1} -eq 9 ] ;then
  thres=30
elif [ ${mm1} -eq 7 ] || [ ${mm1} -eq 8 ] ; then
  thres=35
elif [ ${mm1} -eq 4 ] || [ ${mm1} -eq 11 ] ; then
  thres=20
elif [ ${mm1} -eq 1 ] || [ ${mm1} -eq 2 ] || [ ${mm1} -eq 3 ] || [ ${mm1} -eq 12 ] ; then
  thres=15
fi
echo "mm1=" ${mm1} "cmm1=" ${cmm1} "THRES=" ${thres}


case ${mm1} in \
  05)  th1=25;th2=30;th3=35;th4=35;th5=30;th6=25;th7=20;;
  06)  th1=30;th2=35;th3=35;th4=30;th5=25;th6=20;th7=15;;
  07)  th1=35;th2=35;th3=30;th4=25;th5=20;th6=15;th7=15;;
  08)  th1=35;th2=30;th3=25;th4=20;th5=15;th6=15;th7=15;;
  09)  th1=30;th2=25;th3=20;th4=15;th5=15;th6=15;th7=15;;
  10)  th1=25;th2=20;th3=15;th4=15;th5=15;th6=15;th7=20;;
  11)  th1=20;th2=15;th3=15;th4=15;th5=15;th6=20;th7=25;;
  12)  th1=15;th2=15;th3=15;th4=15;th5=20;th6=25;th7=30;;
  01)  th1=15;th2=15;th3=15;th4=20;th5=25;th6=30;th7=35;;
  02)  th1=15;th2=15;th3=20;th4=25;th5=30;th6=35;th7=35;;
  03)  th1=15;th2=20;th3=25;th4=30;th5=35;th6=35;th7=30;;
  04)  th1=20;th2=25;th3=30;th4=35;th5=35;th6=30;th7=25;;
esac

echo "mm1=" ${mm1} "thresholds:" $th1 $th2 $th3 $th4 $th5 $th6 $th7
#
base=$yy1$mm1$dd1
echo "base=" ${base}
dget=${dget0}/Base_${yy1}${mm1}
mkdir -p ${dget}

##########################

cd ${dwk}

\rm -f ${dwk}/namdat_py
cat << EOF > ${dwk}/namdat_py
base=${yy1}${mm1}
yy1=${yy1}
mm1='${mm1}'
cmm1='${cmm1}'
var='${favar}'
plvar='${plvar}'
pyvar='maximum_2m_temperature_in_the_last_24_hours'
EOF

############### 1. GET  data ###############
\rm -f ss_GET_Year_TX_daily.py_p1
cat ${dwk}/namdat_py ${daux}/ss_GET_Year_TX_daily.py_p1_base > ss_GET_Year_TX_daily.py_p1
${python} ss_GET_Year_TX_daily.py_p1 1>out1 2>out2 &
wait
mv yearly_Tx_daily_13m_base${yy1}${mm1}.grib ${dget}

echo "done, GET data in: " /mypath3/OPER/C3S/Prel_CRON/Module1_Forecast/Forecast/Year/Extremes/Indices_Forecast_Year/Heat_waves/Forecast/GET_data/DATA/Base_${yy1}${mm1}
############### 2. PREL & PLOT  data ###############

\rm -f ${dwk}/namdat
cat << EOF > ${dwk}/namdat
#!/bin/sh
base=${yy1}${mm1}
yy1=${yy1}
mm1=${cmm1}
var=${favar}
plvar='${plvar}'
pyvar='maximum_2m_temperature_in_the_last_24_hours'
thres=${thres}
th1=${th1}
th2=${th2}
th3=${th3}
th4=${th4}
th5=${th5}
th6=${th6}
th7=${th7}
lon0=26.1
lat0=44.4
EOF
#
\rm -f scr_Prel_heat_wave_OK_p2
cat ${dwk}/namdat ${daux}/scr_Prel_heat_wave_OK_p2_base  > scr_Prel_heat_wave_OK_p2
chmod u+x scr_Prel_heat_wave_OK_p2
./scr_Prel_heat_wave_OK_p2
wait
echo "done, plots in: " /mypath3/OPER/C3S/Prel_CRON/Module1_Forecast/Forecast/Year/Extremes/Indices_Forecast_Year/Heat_waves/Forecast/SCR/Plot/PRINT_IZO/${base}
echo "Done, WEB-plots in: " /mypath3/OPER/C3S/WEB_Platform/M1_FORECAST/Year/Sectorial-indicators/HEAT_waves/

#########################################################################
#########################################################################
#########################################################################



